export const CHANGE_NAME = "CHANGE_NAME"
export const CHANGE_PHONE = "CHANGE_PHONE"
export const CHANGE_EMAIL = "CHANGE_EMAIL"
export const CHANGE_DESC = "CHANGE_DESC"
export const CHANGE_IMG = "CHANGE_IMG"